<?php
/**
 * Copyright © MageDevGroup. All rights reserved.
 *
 * @var \MageDevGroup\AdminSso\Block\Adminhtml\Login\Sso $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->isAvailable()): ?>
    <?php $iconUrl = $block->getButtonIconUrl(); ?>
    <div class="magedevgroup-admin-sso">
        <a class="action-secondary magedevgroup-admin-sso-button"
           href="<?= $escaper->escapeUrl($block->getStartUrl()) ?>">
            <?php if ($iconUrl !== null): ?>
                <img class="magedevgroup-admin-sso-icon"
                     src="<?= $escaper->escapeUrl($iconUrl) ?>"
                     alt="" />
            <?php endif; ?>
            <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
        </a>
    </div>
<?php endif; ?>
